// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CorrectOrNotController from "./correct_or_not_controller"
application.register("correct-or-not", CorrectOrNotController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImgZoomController from "./img_zoom_controller"
application.register("img-zoom", ImgZoomController)
